AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/**
    - config/**
    - script/**
  TargetRubyVersion: 2.4.1

StringLiterals:
  Enabled: false

LambdaCall:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/factories/**'
  ExcludedMethods:
    - attributes_table
    - register
    - controller
    - show
    - table_for
    - columns
    - column
    - feature
    - context
    - describe
    - scenario
    - shared_examples_for
    - form
    - inputs
    - shared_examples
    - define

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Naming/PredicateName:
  NamePrefixBlacklist:
    - is_

# Casecmp isn't particularly readable
Performance/Casecmp:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: line_count_based
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

# We don't consider .positive? etc to be that readable
Style/NumericPredicate:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/BlockEndNewline:
  Enabled: false

Layout/CaseIndentation:
  IndentOneStep: true

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 2

# Disabled so that we can write .to_not change { } in Rspec
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - delegate

Style/AsciiComments:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/ClassAndModuleChildren:
  Enabled: false

Style/CollectionMethods:
  Enabled: true

Style/DoubleNegation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false
