name: CI

on: push

jobs:
  build:
    uses: hubbado/workflows/.github/workflows/component-ci_no-docker.yml@main
    secrets:
      BUNDLE_RUBYGEMS__PKG__GITHUB__COM: ${{ secrets.BUNDLE_RUBYGEMS__PKG__GITHUB__COM }}
      BUNDLE_GITHUB__COM: ${{ secrets.BUNDLE_GITHUB__COM }}
